version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - LLAMA_INDEX_STORAGE_DIR=/app/data/index_storage
    depends_on:
      - redis
    volumes:
      - .:/app
      - llama_index_data:/app/data/index_storage
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - LLAMA_INDEX_STORAGE_DIR=/app/data/index_storage
    depends_on:
      - redis
    volumes:
      - .:/app
      - llama_index_data:/app/data/index_storage
    command: celery -A app.celery_app worker --loglevel=info

volumes:
  redis_data:
  llama_index_data: